// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orders.proto

package OrderHistory;

public final class PurchaseHistory {
  private PurchaseHistory() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrdersDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.OrdersData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string email = 1;</code>
     * @return Whether the email field is set.
     */
    boolean hasEmail();
    /**
     * <code>required string email = 1;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>required string email = 1;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>optional string invoicenumber = 2;</code>
     * @return Whether the invoicenumber field is set.
     */
    boolean hasInvoicenumber();
    /**
     * <code>optional string invoicenumber = 2;</code>
     * @return The invoicenumber.
     */
    java.lang.String getInvoicenumber();
    /**
     * <code>optional string invoicenumber = 2;</code>
     * @return The bytes for invoicenumber.
     */
    com.google.protobuf.ByteString
        getInvoicenumberBytes();

    /**
     * <code>optional string model = 3;</code>
     * @return Whether the model field is set.
     */
    boolean hasModel();
    /**
     * <code>optional string model = 3;</code>
     * @return The model.
     */
    java.lang.String getModel();
    /**
     * <code>optional string model = 3;</code>
     * @return The bytes for model.
     */
    com.google.protobuf.ByteString
        getModelBytes();

    /**
     * <code>optional string category = 4;</code>
     * @return Whether the category field is set.
     */
    boolean hasCategory();
    /**
     * <code>optional string category = 4;</code>
     * @return The category.
     */
    java.lang.String getCategory();
    /**
     * <code>optional string category = 4;</code>
     * @return The bytes for category.
     */
    com.google.protobuf.ByteString
        getCategoryBytes();

    /**
     * <code>optional int32 amount = 5;</code>
     * @return Whether the amount field is set.
     */
    boolean hasAmount();
    /**
     * <code>optional int32 amount = 5;</code>
     * @return The amount.
     */
    int getAmount();

    /**
     * <code>optional string purchasedate = 6;</code>
     * @return Whether the purchasedate field is set.
     */
    boolean hasPurchasedate();
    /**
     * <code>optional string purchasedate = 6;</code>
     * @return The purchasedate.
     */
    java.lang.String getPurchasedate();
    /**
     * <code>optional string purchasedate = 6;</code>
     * @return The bytes for purchasedate.
     */
    com.google.protobuf.ByteString
        getPurchasedateBytes();

    /**
     * <code>optional string discountavailed = 7;</code>
     * @return Whether the discountavailed field is set.
     */
    boolean hasDiscountavailed();
    /**
     * <code>optional string discountavailed = 7;</code>
     * @return The discountavailed.
     */
    java.lang.String getDiscountavailed();
    /**
     * <code>optional string discountavailed = 7;</code>
     * @return The bytes for discountavailed.
     */
    com.google.protobuf.ByteString
        getDiscountavailedBytes();
  }
  /**
   * Protobuf type {@code protobuf.OrdersData}
   */
  public static final class OrdersData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.OrdersData)
      OrdersDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OrdersData.newBuilder() to construct.
    private OrdersData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OrdersData() {
      email_ = "";
      invoicenumber_ = "";
      model_ = "";
      category_ = "";
      purchasedate_ = "";
      discountavailed_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OrdersData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OrdersData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              email_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              invoicenumber_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              model_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              category_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              amount_ = input.readInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              purchasedate_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              discountavailed_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OrderHistory.PurchaseHistory.internal_static_protobuf_OrdersData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OrderHistory.PurchaseHistory.internal_static_protobuf_OrdersData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OrderHistory.PurchaseHistory.OrdersData.class, OrderHistory.PurchaseHistory.OrdersData.Builder.class);
    }

    private int bitField0_;
    public static final int EMAIL_FIELD_NUMBER = 1;
    private volatile java.lang.Object email_;
    /**
     * <code>required string email = 1;</code>
     * @return Whether the email field is set.
     */
    @java.lang.Override
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string email = 1;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string email = 1;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INVOICENUMBER_FIELD_NUMBER = 2;
    private volatile java.lang.Object invoicenumber_;
    /**
     * <code>optional string invoicenumber = 2;</code>
     * @return Whether the invoicenumber field is set.
     */
    @java.lang.Override
    public boolean hasInvoicenumber() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string invoicenumber = 2;</code>
     * @return The invoicenumber.
     */
    @java.lang.Override
    public java.lang.String getInvoicenumber() {
      java.lang.Object ref = invoicenumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          invoicenumber_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string invoicenumber = 2;</code>
     * @return The bytes for invoicenumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInvoicenumberBytes() {
      java.lang.Object ref = invoicenumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        invoicenumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MODEL_FIELD_NUMBER = 3;
    private volatile java.lang.Object model_;
    /**
     * <code>optional string model = 3;</code>
     * @return Whether the model field is set.
     */
    @java.lang.Override
    public boolean hasModel() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string model = 3;</code>
     * @return The model.
     */
    @java.lang.Override
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          model_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string model = 3;</code>
     * @return The bytes for model.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CATEGORY_FIELD_NUMBER = 4;
    private volatile java.lang.Object category_;
    /**
     * <code>optional string category = 4;</code>
     * @return Whether the category field is set.
     */
    @java.lang.Override
    public boolean hasCategory() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string category = 4;</code>
     * @return The category.
     */
    @java.lang.Override
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          category_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string category = 4;</code>
     * @return The bytes for category.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 5;
    private int amount_;
    /**
     * <code>optional int32 amount = 5;</code>
     * @return Whether the amount field is set.
     */
    @java.lang.Override
    public boolean hasAmount() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 amount = 5;</code>
     * @return The amount.
     */
    @java.lang.Override
    public int getAmount() {
      return amount_;
    }

    public static final int PURCHASEDATE_FIELD_NUMBER = 6;
    private volatile java.lang.Object purchasedate_;
    /**
     * <code>optional string purchasedate = 6;</code>
     * @return Whether the purchasedate field is set.
     */
    @java.lang.Override
    public boolean hasPurchasedate() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string purchasedate = 6;</code>
     * @return The purchasedate.
     */
    @java.lang.Override
    public java.lang.String getPurchasedate() {
      java.lang.Object ref = purchasedate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          purchasedate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string purchasedate = 6;</code>
     * @return The bytes for purchasedate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPurchasedateBytes() {
      java.lang.Object ref = purchasedate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        purchasedate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DISCOUNTAVAILED_FIELD_NUMBER = 7;
    private volatile java.lang.Object discountavailed_;
    /**
     * <code>optional string discountavailed = 7;</code>
     * @return Whether the discountavailed field is set.
     */
    @java.lang.Override
    public boolean hasDiscountavailed() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string discountavailed = 7;</code>
     * @return The discountavailed.
     */
    @java.lang.Override
    public java.lang.String getDiscountavailed() {
      java.lang.Object ref = discountavailed_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          discountavailed_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string discountavailed = 7;</code>
     * @return The bytes for discountavailed.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDiscountavailedBytes() {
      java.lang.Object ref = discountavailed_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        discountavailed_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasEmail()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, email_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, invoicenumber_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, model_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, category_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, amount_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, purchasedate_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, discountavailed_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, email_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, invoicenumber_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, model_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, category_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, amount_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, purchasedate_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, discountavailed_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof OrderHistory.PurchaseHistory.OrdersData)) {
        return super.equals(obj);
      }
      OrderHistory.PurchaseHistory.OrdersData other = (OrderHistory.PurchaseHistory.OrdersData) obj;

      if (hasEmail() != other.hasEmail()) return false;
      if (hasEmail()) {
        if (!getEmail()
            .equals(other.getEmail())) return false;
      }
      if (hasInvoicenumber() != other.hasInvoicenumber()) return false;
      if (hasInvoicenumber()) {
        if (!getInvoicenumber()
            .equals(other.getInvoicenumber())) return false;
      }
      if (hasModel() != other.hasModel()) return false;
      if (hasModel()) {
        if (!getModel()
            .equals(other.getModel())) return false;
      }
      if (hasCategory() != other.hasCategory()) return false;
      if (hasCategory()) {
        if (!getCategory()
            .equals(other.getCategory())) return false;
      }
      if (hasAmount() != other.hasAmount()) return false;
      if (hasAmount()) {
        if (getAmount()
            != other.getAmount()) return false;
      }
      if (hasPurchasedate() != other.hasPurchasedate()) return false;
      if (hasPurchasedate()) {
        if (!getPurchasedate()
            .equals(other.getPurchasedate())) return false;
      }
      if (hasDiscountavailed() != other.hasDiscountavailed()) return false;
      if (hasDiscountavailed()) {
        if (!getDiscountavailed()
            .equals(other.getDiscountavailed())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasEmail()) {
        hash = (37 * hash) + EMAIL_FIELD_NUMBER;
        hash = (53 * hash) + getEmail().hashCode();
      }
      if (hasInvoicenumber()) {
        hash = (37 * hash) + INVOICENUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getInvoicenumber().hashCode();
      }
      if (hasModel()) {
        hash = (37 * hash) + MODEL_FIELD_NUMBER;
        hash = (53 * hash) + getModel().hashCode();
      }
      if (hasCategory()) {
        hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
        hash = (53 * hash) + getCategory().hashCode();
      }
      if (hasAmount()) {
        hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getAmount();
      }
      if (hasPurchasedate()) {
        hash = (37 * hash) + PURCHASEDATE_FIELD_NUMBER;
        hash = (53 * hash) + getPurchasedate().hashCode();
      }
      if (hasDiscountavailed()) {
        hash = (37 * hash) + DISCOUNTAVAILED_FIELD_NUMBER;
        hash = (53 * hash) + getDiscountavailed().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static OrderHistory.PurchaseHistory.OrdersData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OrderHistory.PurchaseHistory.OrdersData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OrderHistory.PurchaseHistory.OrdersData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OrderHistory.PurchaseHistory.OrdersData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OrderHistory.PurchaseHistory.OrdersData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OrderHistory.PurchaseHistory.OrdersData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OrderHistory.PurchaseHistory.OrdersData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OrderHistory.PurchaseHistory.OrdersData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static OrderHistory.PurchaseHistory.OrdersData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static OrderHistory.PurchaseHistory.OrdersData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static OrderHistory.PurchaseHistory.OrdersData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OrderHistory.PurchaseHistory.OrdersData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(OrderHistory.PurchaseHistory.OrdersData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.OrdersData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.OrdersData)
        OrderHistory.PurchaseHistory.OrdersDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return OrderHistory.PurchaseHistory.internal_static_protobuf_OrdersData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return OrderHistory.PurchaseHistory.internal_static_protobuf_OrdersData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OrderHistory.PurchaseHistory.OrdersData.class, OrderHistory.PurchaseHistory.OrdersData.Builder.class);
      }

      // Construct using OrderHistory.PurchaseHistory.OrdersData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        invoicenumber_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        model_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        category_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        amount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        purchasedate_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        discountavailed_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return OrderHistory.PurchaseHistory.internal_static_protobuf_OrdersData_descriptor;
      }

      @java.lang.Override
      public OrderHistory.PurchaseHistory.OrdersData getDefaultInstanceForType() {
        return OrderHistory.PurchaseHistory.OrdersData.getDefaultInstance();
      }

      @java.lang.Override
      public OrderHistory.PurchaseHistory.OrdersData build() {
        OrderHistory.PurchaseHistory.OrdersData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public OrderHistory.PurchaseHistory.OrdersData buildPartial() {
        OrderHistory.PurchaseHistory.OrdersData result = new OrderHistory.PurchaseHistory.OrdersData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.email_ = email_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.invoicenumber_ = invoicenumber_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.model_ = model_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.category_ = category_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.amount_ = amount_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.purchasedate_ = purchasedate_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.discountavailed_ = discountavailed_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OrderHistory.PurchaseHistory.OrdersData) {
          return mergeFrom((OrderHistory.PurchaseHistory.OrdersData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OrderHistory.PurchaseHistory.OrdersData other) {
        if (other == OrderHistory.PurchaseHistory.OrdersData.getDefaultInstance()) return this;
        if (other.hasEmail()) {
          bitField0_ |= 0x00000001;
          email_ = other.email_;
          onChanged();
        }
        if (other.hasInvoicenumber()) {
          bitField0_ |= 0x00000002;
          invoicenumber_ = other.invoicenumber_;
          onChanged();
        }
        if (other.hasModel()) {
          bitField0_ |= 0x00000004;
          model_ = other.model_;
          onChanged();
        }
        if (other.hasCategory()) {
          bitField0_ |= 0x00000008;
          category_ = other.category_;
          onChanged();
        }
        if (other.hasAmount()) {
          setAmount(other.getAmount());
        }
        if (other.hasPurchasedate()) {
          bitField0_ |= 0x00000020;
          purchasedate_ = other.purchasedate_;
          onChanged();
        }
        if (other.hasDiscountavailed()) {
          bitField0_ |= 0x00000040;
          discountavailed_ = other.discountavailed_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasEmail()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OrderHistory.PurchaseHistory.OrdersData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OrderHistory.PurchaseHistory.OrdersData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object email_ = "";
      /**
       * <code>required string email = 1;</code>
       * @return Whether the email field is set.
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string email = 1;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            email_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string email = 1;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string email = 1;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string email = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000001);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>required string email = 1;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        email_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object invoicenumber_ = "";
      /**
       * <code>optional string invoicenumber = 2;</code>
       * @return Whether the invoicenumber field is set.
       */
      public boolean hasInvoicenumber() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string invoicenumber = 2;</code>
       * @return The invoicenumber.
       */
      public java.lang.String getInvoicenumber() {
        java.lang.Object ref = invoicenumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            invoicenumber_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string invoicenumber = 2;</code>
       * @return The bytes for invoicenumber.
       */
      public com.google.protobuf.ByteString
          getInvoicenumberBytes() {
        java.lang.Object ref = invoicenumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          invoicenumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string invoicenumber = 2;</code>
       * @param value The invoicenumber to set.
       * @return This builder for chaining.
       */
      public Builder setInvoicenumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        invoicenumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string invoicenumber = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearInvoicenumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        invoicenumber_ = getDefaultInstance().getInvoicenumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional string invoicenumber = 2;</code>
       * @param value The bytes for invoicenumber to set.
       * @return This builder for chaining.
       */
      public Builder setInvoicenumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        invoicenumber_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object model_ = "";
      /**
       * <code>optional string model = 3;</code>
       * @return Whether the model field is set.
       */
      public boolean hasModel() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string model = 3;</code>
       * @return The model.
       */
      public java.lang.String getModel() {
        java.lang.Object ref = model_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            model_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string model = 3;</code>
       * @return The bytes for model.
       */
      public com.google.protobuf.ByteString
          getModelBytes() {
        java.lang.Object ref = model_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          model_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string model = 3;</code>
       * @param value The model to set.
       * @return This builder for chaining.
       */
      public Builder setModel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        model_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string model = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearModel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        model_ = getDefaultInstance().getModel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string model = 3;</code>
       * @param value The bytes for model to set.
       * @return This builder for chaining.
       */
      public Builder setModelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        model_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object category_ = "";
      /**
       * <code>optional string category = 4;</code>
       * @return Whether the category field is set.
       */
      public boolean hasCategory() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string category = 4;</code>
       * @return The category.
       */
      public java.lang.String getCategory() {
        java.lang.Object ref = category_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            category_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string category = 4;</code>
       * @return The bytes for category.
       */
      public com.google.protobuf.ByteString
          getCategoryBytes() {
        java.lang.Object ref = category_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          category_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string category = 4;</code>
       * @param value The category to set.
       * @return This builder for chaining.
       */
      public Builder setCategory(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        category_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string category = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCategory() {
        bitField0_ = (bitField0_ & ~0x00000008);
        category_ = getDefaultInstance().getCategory();
        onChanged();
        return this;
      }
      /**
       * <code>optional string category = 4;</code>
       * @param value The bytes for category to set.
       * @return This builder for chaining.
       */
      public Builder setCategoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        category_ = value;
        onChanged();
        return this;
      }

      private int amount_ ;
      /**
       * <code>optional int32 amount = 5;</code>
       * @return Whether the amount field is set.
       */
      @java.lang.Override
      public boolean hasAmount() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional int32 amount = 5;</code>
       * @return The amount.
       */
      @java.lang.Override
      public int getAmount() {
        return amount_;
      }
      /**
       * <code>optional int32 amount = 5;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(int value) {
        bitField0_ |= 0x00000010;
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 amount = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        bitField0_ = (bitField0_ & ~0x00000010);
        amount_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object purchasedate_ = "";
      /**
       * <code>optional string purchasedate = 6;</code>
       * @return Whether the purchasedate field is set.
       */
      public boolean hasPurchasedate() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional string purchasedate = 6;</code>
       * @return The purchasedate.
       */
      public java.lang.String getPurchasedate() {
        java.lang.Object ref = purchasedate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            purchasedate_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string purchasedate = 6;</code>
       * @return The bytes for purchasedate.
       */
      public com.google.protobuf.ByteString
          getPurchasedateBytes() {
        java.lang.Object ref = purchasedate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          purchasedate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string purchasedate = 6;</code>
       * @param value The purchasedate to set.
       * @return This builder for chaining.
       */
      public Builder setPurchasedate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        purchasedate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string purchasedate = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPurchasedate() {
        bitField0_ = (bitField0_ & ~0x00000020);
        purchasedate_ = getDefaultInstance().getPurchasedate();
        onChanged();
        return this;
      }
      /**
       * <code>optional string purchasedate = 6;</code>
       * @param value The bytes for purchasedate to set.
       * @return This builder for chaining.
       */
      public Builder setPurchasedateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        purchasedate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object discountavailed_ = "";
      /**
       * <code>optional string discountavailed = 7;</code>
       * @return Whether the discountavailed field is set.
       */
      public boolean hasDiscountavailed() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional string discountavailed = 7;</code>
       * @return The discountavailed.
       */
      public java.lang.String getDiscountavailed() {
        java.lang.Object ref = discountavailed_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            discountavailed_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string discountavailed = 7;</code>
       * @return The bytes for discountavailed.
       */
      public com.google.protobuf.ByteString
          getDiscountavailedBytes() {
        java.lang.Object ref = discountavailed_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          discountavailed_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string discountavailed = 7;</code>
       * @param value The discountavailed to set.
       * @return This builder for chaining.
       */
      public Builder setDiscountavailed(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        discountavailed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string discountavailed = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDiscountavailed() {
        bitField0_ = (bitField0_ & ~0x00000040);
        discountavailed_ = getDefaultInstance().getDiscountavailed();
        onChanged();
        return this;
      }
      /**
       * <code>optional string discountavailed = 7;</code>
       * @param value The bytes for discountavailed to set.
       * @return This builder for chaining.
       */
      public Builder setDiscountavailedBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        discountavailed_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.OrdersData)
    }

    // @@protoc_insertion_point(class_scope:protobuf.OrdersData)
    private static final OrderHistory.PurchaseHistory.OrdersData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new OrderHistory.PurchaseHistory.OrdersData();
    }

    public static OrderHistory.PurchaseHistory.OrdersData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<OrdersData>
        PARSER = new com.google.protobuf.AbstractParser<OrdersData>() {
      @java.lang.Override
      public OrdersData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrdersData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OrdersData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OrdersData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public OrderHistory.PurchaseHistory.OrdersData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_OrdersData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_OrdersData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014orders.proto\022\010protobuf\"\222\001\n\nOrdersData\022" +
      "\r\n\005email\030\001 \002(\t\022\025\n\rinvoicenumber\030\002 \001(\t\022\r\n" +
      "\005model\030\003 \001(\t\022\020\n\010category\030\004 \001(\t\022\016\n\006amount" +
      "\030\005 \001(\005\022\024\n\014purchasedate\030\006 \001(\t\022\027\n\017discount" +
      "availed\030\007 \001(\tB\037\n\014OrderHistoryB\017PurchaseH" +
      "istory"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuf_OrdersData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_OrdersData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_OrdersData_descriptor,
        new java.lang.String[] { "Email", "Invoicenumber", "Model", "Category", "Amount", "Purchasedate", "Discountavailed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
